name: autolibdz
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.13.3
  jwt_decode: ^0.3.1
  shared_preferences: ^2.0.5
  flutter_switch: ^0.3.1
  anim_search_bar: ^2.0.1
  intl: ^0.17.0
  google_maps_flutter: ^2.0.6
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - img/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
  
